services:
  mysql:
    image: mysql:8.0
    container_name: go_app_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vending_machine
    volumes:
      - ./backend/drivers/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    container_name: go-vending-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: go_app_backend
    volumes:
      - ./backend:/app
      - /app/tmp
    working_dir: /app
    command: air
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: vending_machine
      SECRET_KEY: "sirichai-44-secret-key"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
